# UI/Display constants
PANEL_WIDTH = None
QUESTION_BORDER_PANEL_COLOR = "blue"
CORRECT_ANSWER_BORDER_PANEL_COLOR = "green"
INCORRECT_ANSWER_BORDER_PANEL_COLOR = "red"
MODEL_RESPONSE_BORDER_PANEL_COLOR = "yellow"
DEBUG_BORDER_PANEL_COLOR = "red"

# Other configuration constants
MAX_REFRESH_RATE = 10
DEFAULT_TIMEOUT_SECONDS = 30
